# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
