# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ticker',
        ),
        migrations.AddField(
            model_name='stock',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Company'),
            preserve_default=False,
        ),
    ]
