# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170630_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_file', models.FileField(upload_to='')),
            ],
        ),
    ]
